# cargo-vacuity-count.awk — how many tests did that run ACTUALLY execute?
#
# GENERATED COPY. The source of record is
# qontinui-claude-config/scripts/lib/cargo-vacuity.sh, and
# qontinui-claude-config/scripts/lint-cargo-verification-form.py asserts the
# marker-delimited block below is byte-identical to it (after dedent). Edit the
# source, re-copy, and re-run that lint; do not edit this file in place.
#
# WHY A COPY AT ALL, since a copy is the thing that drifts. This workflow runs on
# a GitHub runner that never checks out qontinui-claude-config, so it cannot
# source the library. The alternatives were weighed and rejected: checking out
# the config repo as a sibling would let one config-repo edit red three unrelated
# repos, and publishing the oracle as a composite action is a distribution
# project rather than a line of CI. Inlining is what coord already does and what
# visibly works; the cost is transcription drift, which is mechanically
# checkable, so it is checked.
#
# Output: "<tests_ran> <summary_lines>" on one line, always, exit 0 always.
# Reads BOTH grammars — libtest `test result: ok. N passed;` and nextest
# `Summary [...] N tests run:` — because coord's own shipped floor anchors
# /^test result: ok\./ and matches the nextest line nowhere, which is why the
# job that needed a floor most had none.
#
# Plan: 2026-09-06-rust-verification-green-but-vacuous, Phase 4.
#
# source-sha256: f4ce07d595b6065543eb4613dbffde334e7531cb542b0a01b67aa1a8cd5de98c
#   The digest of the marker-delimited block below. This repo's own CI asserts its
#   file still matches it (in-repo tampering), and qontinui-claude-config's
#   lint-cargo-verification-form.py asserts BOTH the block and this digest still
#   match the source (drift from the source of record) whenever both repos are
#   checked out side by side. Neither half alone is a cross-repo gate; that is
#   plan 2026-09-06-cross-repo-transcription-drift-has-no-ci-gate's subject.

# >>> CARGO_VACUITY_AWK v1 (source of record: qontinui-claude-config/scripts/lib/cargo-vacuity.sh) >>>
{
  line = $0
  gsub(/\033\[[0-9;]*[a-zA-Z]/, "", line)
  if (line ~ /test result:/) {
    n = split(line, w, /[ \t]+/)
    for (i = 1; i < n; i++) {
      if (w[i+1] ~ /^passed/) ran += w[i] + 0
      if (w[i+1] ~ /^failed/) ran += w[i] + 0
    }
    summaries++
  } else if (line ~ /Summary \[/ && line ~ /tests? run:/) {
    if (match(line, /[0-9]+ tests? run:/)) ran += substr(line, RSTART, RLENGTH) + 0
    summaries++
  }
}
END { printf "%d %d\n", ran + 0, summaries + 0 }
# <<< CARGO_VACUITY_AWK v1 <<<
